# Generated by Django 5.2.6 on 2025-09-29 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_remove_assignment_teammates_alter_student_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="todo.subject",
            ),
        ),
    ]
