# Generated by Django 5.2.6 on 2025-09-29 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_assignment_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="todo.subject",
            ),
        ),
    ]
