# Generated by Django 5.2.6 on 2025-09-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_assignment_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "In progress"),
                    (2, "Completed"),
                    (3, "Failed"),
                ],
                default=0,
            ),
        ),
    ]
